# Generated by Django 4.1.2 on 2023-06-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0002_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
