# Generated by Django 4.1.2 on 2023-06-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_alter_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
