# Generated by Django 4.1.2 on 2023-06-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_alter_devis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devis.client'),
        ),
    ]
