# Generated by Django 4.1.2 on 2023-06-18 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0005_devis_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='taches',
        ),
        migrations.AddField(
            model_name='tache',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='devis.devis'),
        ),
    ]
