# Generated by Django 4.1.2 on 2023-06-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0006_remove_devis_taches_tache_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='numero',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
